version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "yourRootPassword"
      MYSQL_DATABASE: "absentify"
      MYSQL_USER: "absentifyadmin"
      MYSQL_PASSWORD: "yourRootPassword"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=caching_sha2_password

volumes:
  mysql-data:
